commits.message = "chore: update ${artifactName} from ${currentVersion} to ${nextVersion}"

updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala-library", version = "2.12." },
  { groupId = "org.scala-sbt",  artifactId = "sbt",           version = "1." }
]
