name: build

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JVM_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt/launchers
            ~/.sbt/boot
            ~/.sbt/preloaded
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      - name: Test
        run: |
          sbt \
            "all headerCheck" \
            "all scalafmtSbtCheck" \
            "all scalafmtCheckAll" \
            "all Compile / gatlingScalafixCheck" \
            "all Test / gatlingScalafixCheck" \
            "all gatlingScalafixCheck" \
            "test" \
            "scripted"
