name: build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Test
        run: |
          sbt \
            "all headerCheck scalafmtSbtCheck scalafmtCheckAll" \
            "scalafixAll --check" \
            "test" \
            "scripted"
